import cron from "node-cron";
import { query } from "../config/db.js";
import { sendDailySummary } from "./email.js";
import { serializeReport } from "./serializers.js";

function toRequiredDate(value?: string) {
  return new Date(value ?? new Date().toISOString());
}

export function startDailySummary() {
  if (process.env.DISABLE_DAILY_SUMMARY === "true") {
    return;
  }

  cron.schedule("5 0 * * *", async () => {
    try {
      const insert = await query(
        `
          INSERT INTO reports (title, description, meta)
          VALUES ($1, $2, $3::jsonb)
          RETURNING id, title, description, meta, generated_at, created_at, updated_at, generated_by
        `,
        [
          "Daily summary",
          "Automated daily report generated by Ved Logistics.",
          JSON.stringify({ generatedAt: new Date().toISOString() }),
        ]
      );

      const report = serializeReport(insert.rows[0]);
      await sendDailySummary({
        id: report._id,
        title: report.title,
        description: report.description,
        meta: report.meta,
        generatedAt: toRequiredDate(report.generatedAt),
        createdAt: toRequiredDate(report.createdAt),
        updatedAt: toRequiredDate(report.updatedAt),
        generatedBy: report.generatedBy,
      });

      console.log("Daily summary email sent");
    } catch (error) {
      console.error("Failed to send daily summary", error);
    }
  });
}
